project:
  type: website
website:
  cookie-consent: true
  google-analytics: "G-MKT52KHL7C"
  title: "STUDY**STATS**"
  navbar:
    background: dark
    logo: "logo/StudyStats_Logo Files/CMYK/second_logo_portrait/White/white_big_C.png"
    logo-alt: "StudyStats Logo"
    left:
      - text: "Landing"
        href: index.qmd
      - text: "How it works"
        href: how_it_works.qmd
      - text: "Blog"
        href: blog/index.qmd
      - text: "About"
        href: about.qmd
      - text: "Mission"
        href: mission.qmd
      - text: "Activities"
        href: details.qmd
#      - text: "Rates"
#        href: rates.qmd
      - text: "Contact"
        href: contact.qmd
format:
  html:
    theme: "styles.css"
    include-before-body: before.html
    include-after: after.html
    output-dir: public
editor: visual
