project:
  type: website
  title: "StudyStats: Expert Statistical Consulting"
website:
  # Optionally repeat (or override) title and description here
  title: "STUDYSTATS"
  description: "StudyStats: Expert statistical consulting, blog, and tools."
  cookie-consent: true
  google-analytics: "G-MKT52KHL7C"
  navbar:
    background: dark
    logo: "logo/StudyStats_Logo Files/CMYK/second_logo_portrait/White/white_big_C.png"
    logo-alt: "StudyStats Logo"
    left:
      - text: "Landing"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "How it works"
        href: how_it_works.qmd
      - text: "Blog"
        href: blog/index.qmd
#      - text: "Mission"
#        href: mission.qmd
#      - text: "Activities"
#        href: details.qmd
#      - text: "Rates"
#        href: rates.qmd
      - text: "Tools"
        href: tools/index.qmd
      - text: "Friends of StudyStats"
        href: friends.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: "styles.css"
    include-before-body: before.html
    include-after: after.html
    output-dir: public
    citations-hover: true
    footnotes-hover: true
    smooth-scroll: true
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    reference-location: margin
    citation-location: margin
editor: source

# Global citation settings
cite-method: citeproc
csl: https://www.zotero.org/styles/apa-6th-edition
