---
title: ""
---

## Mission

Welcome to Study**Stats**. We were founded to meet the distinctive challenges of health professionals, especially Medical Doctors pursuing their Master of Medicine. Recognizing the demands on their time and resources during their specialisation journey, we strive to offer effective solutions for their statistical needs throughout the research project phase. Study**Stats** is dedicated to easing the burden during the research phase of your specialisation.

Our **mission** is to provide a comprehensive service, that, aswell as providing robust biostatistical services, enhances your workflow by creating publication-ready tables, figures , and writing that can seamlessly integrate into your projects. We are committed to offering support throughout the entire research journey, ensuring the accurate interpretation, discussion, and presentation of your results to the standards of peer-reviewed journals and the advancement of evidence-based practice.

While we operate as a for-profit entity, we consider ourselves integral contributors to the enhancement of evidence-based practice. We envision Study**Stats** as a key ally in maintaining the enthusiasm of medical professionals for their projects, the quality of the projects and ultimately the information generated to improve patient outcomes.